version: '3'
services:
  web:
    build:
      context: web
      target: develop
      dockerfile: Dockerfile.local
    command: >
      bash -c "yarn install && yarn run dev --host"
    volumes:
      - "./web/app:/svelte_app"
    ports:
      - "5173:5173"

  backend:
    build:
      context: server/app
      target: develop
      dockerfile: Dockerfile.local
    volumes:
      - "./server/app:/server"
    command: >
      bash -c "yarn install && yarn run start"
    ports:
      - "3000:3000"


