name: backend CI

on:
  push:
    paths:
      - "server/app/**"
      - "!server/app/Dockerfile**"
      - ".github/workflows/backend.yml"
  pull_request:
    types: [opened, reopened, synchronize, review_requested]
    paths:
      - "server/app/**"
      - ".github/workflows/backend_container.yml"

defaults:
  run:
    working-directory: server/app

jobs:
  lint:
    runs-on: ubuntu-latest
    if: >-
      ${{
        github.event.action != 'synchronize' ||
        github.run_attempt != 1
      }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: yarn install
      - run: yarn lint

  build:
    runs-on: ubuntu-latest
    if: >-
      ${{
        github.event.action != 'synchronize' ||
        github.run_attempt != 1
      }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: yarn install
      - run: yarn build
