name: backend container build test

on:
  pull_request:
    types: [opened, reopened, review_requested]
    paths:
      - "server/app/**"

defaults:
  run:
    working-directory: server/app

jobs:
  container:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - name: Build local container
        run: docker buildx build --platform linux/amd64,linux/arm64 -f Dockerfile.local .
      - name: Build product container
        run: docker buildx build --platform linux/amd64,linux/arm64 .
